apiVersion: v1
kind: Pod
metadata:
  name: test-pod-amd
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
  containers:
  - name: arch-amd
    image: ttl.sh/ben-multi-arch-image:multi
    
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-arm
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - arm64
  containers:
  - name: arch-arm
    image: ttl.sh/ben-multi-arch-image:multi
